from nlgeval import NLGEval

n=NLGEval(False,True,True)
scores = n.compute_metrics(ref_list=[
        [
            "this is one reference sentence for sentence1",
            "this is a reference sentence for sentence2 which was generated by your model"
        ],
        [
            "this is one more reference sentence for sentence1",
            "this is the second reference sentence for sentence2"
        ],
    ],
        hyp_list=[
            "this is the model generated sentence1 which seems good enough",
            "this is sentence2 which has been generated by your model"
        ]
    )
print(scores)